### ISSUE TITLE
selecting todo item from the todo list panel - xml file related TODO hides the title until vscode restart

### ISSUE THREAD

**Issue by fssrepository** [Gruntfuggly/todo-tree#101]
version: 0.0.107

Fortunately, I have changed my highlight settings, which clearly shows that some <!-- has been included in the TODO line.

Left side panel showed the TODO title previously, after clicking the line is there with the tick, but the title disappeared.

![image](https://user-images.githubusercontent.com/45578746/49409005-1c16a500-f75f-11e8-8ffd-f50fd53b1d2a.png)

Clicking on java related TODO it shows java setting page, instead of the file, sometimes it was loading properly and highlights the TODO message.

**Comment by Gruntfuggly** [comment]
This is because it is matching newlines in the whitespace part of the regular expression.

Try changing `todo-tree.regex` to:
`"((//|#|<!--|;|/\\*)[ \t]*($TAGS)+|^[ \t]*- \\[ \\])"`

I'll try and work out a proper fix...

**Comment by fssrepository** [comment]
I personally feel, you should highlight from the TODO word without including // <! - - etc.

I never seen in any software before. So the whole regex can be simpilified by TODO:\s+ or something. In VsCode there is a regex search option in the document, i never used it before, but i now simply love it. (ctrl+s third button - by $1... you can even replace by regex groups

**Comment by Gruntfuggly** [comment]
There is an option to change the highlight - you can set 
`todo-tree.defaultHighlight` to 
```
    "todo-tree.defaultHighlight": {
        "type": "tag"
    },
```
where type can be "tag", "text", or "line" - see https://github.com/Gruntfuggly/todo-tree#highlighting

Multiline support raises lots of issues, so support may never happen. 

You're free to change the regex however you like - that's why it is configurable. 😁 

I agree that the default regex is overcomplicated, but unfortunately, because it has to search files without being aware of each file's language, it needs to include comment characters for any you might be interested in.
