### ISSUE TITLE
Could you show us a specific example?

### ISSUE THREAD

**Issue by soljohnston777** [Gruntfuggly/todo-tree#13]
"The extension can be customised as follows:
todo-tree.regex"

Could you show us the regular expression you are using for TODO or FIXME as an example of how this works.  I know regular expressions, but it is nice to have a base to work off from to make our own TODO1 or whatever we may make for priorities.  

Actually - if you think about it this could be your standard version and people could "buy" an advanced version where they could make their own custom priority extensions like TODO1, 2, 3 etc. with colors options....  if you were thinking of making money on this.  

Great plugin - I use it all the time.  I see it used in all the main libraries too!

Thanks!

**Comment by Gruntfuggly** [comment]
Hi there - the default should be displayed in the settings in the comment part? The tricky part is that it's a rust regex, not a standard javascript (because ripgrep is a rust application). Saying that, I've not noticed much in the way of differences, because the default regex is fairly simple anyway.

It's "(//|#|<!--|;)\\s*(TODO|FIXME)" - the first part contained in brackets **(//|#"<!--|;)** matches the various comment characters. The next bit **\\\s*** allows any amount of whitespace, and the last bit in brackets **(TODO|FIXME)** matches the tags. So if you want to add new tags, add them to the third section, separated by vertical bars. 

If you then set something like "todo-tree.iconColours": { "TODO": "red", "FIXME": "green"} you'll get coloured icons for the tags that match. 

I'm not worried about making money from it 8-) - I wrote it for my own use and thought it might be useful for others. Glad you're finding it useful!
