### ISSUE TITLE
Globs are not relative to workspace root

### ISSUE THREAD

**Issue by jahewson** [Gruntfuggly/todo-tree#130]
I'm trying to exclude a `test` folder in the workspace root:

```json
  "todo-tree.excludeGlobs": [
    "test/**"
  ]
```

But I have other nested `test` folders elsewhere in the workspace which I don't want excluded, so `**/test/**` is not a suitable alternative.

Also, because matches are happening on the full path, that means that any folder outside the project can affect the glob matches! So if I happen to have my workspace in `/home/john/test/foo` everything gets excluded.

**Comment by Gruntfuggly** [comment]
Would it work if you put the full path to the test folder you want to exclude? 

I'm not sure what the solution is - I could add support for placeholder substitution (eg `${workspaceRoot}`) in the glob configuration?

**Comment by jahewson** [comment]
Can VSCode's built-in glob support be used?

If not, a minimal fix would be to strip the current value of `workspaceFolder` from the beginning of the path being matched, rather than substituting it in as there's no reason to want to match on folders outside the workspace.

**Comment by Gruntfuggly** [comment]
I think I see what the problem is - unfortunately, it uses full paths to make the tree handling simpler.

I could add an option to make the globs relative - I'll try some things out...

I assume that you have too many folders to make `todo-tree.includeGlobs` useful?

**Comment by somewhatabstract** [comment]
We could change things so that `todo-tree` auto puts the root folder onto the front of all globs? 

I also noted that in my giant project, it would be really nice if the excluded globs were added to the ripgrep execution; I see currently the code looks at a non-existant `globs` setting from the configuration for controlling such things, so ripgrep parses EVERYTHING, and then `todo-tree` applies the included and excluded globs.

**Comment by somewhatabstract** [comment]
I might have a look at addressing these issues.

**Comment by Thalos12** [comment]
Looking at the user guide of ripgrep, under the [Automatic filtering section](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#automatic-filtering), it is explained that you can use `.gitignore`, '.ignore` and '.rgignore` files to define which files/folders to exclude (and, for me, it works). Isn't it something worth mentioning as an alternative to `"todo-tree.excludeGlobs"`? (which, for me, did not work at all, ripgrep would always try to search two very large directories I wanted to exclude)

**Comment by Gruntfuggly** [comment]
@Thalos12 - @somewhatabstract contributed a change which passes the exclude globs to ripgrep, so hopefully that will help.

**Comment by Thalos12** [comment]
Thanks! I will try again as soon as I can.

**Comment by Gruntfuggly** [comment]
@jahewson - do you still have the issue or have you found a workaround? If not, I'll add an option to remove the workspace root from the filenames for glob matching.

**Comment by Thalos12** [comment]
@Gruntfuggly - I tried again in the very large directory (where two subdirectories are >50GB) excluding all `csv` or `cat` files (as they contain only numbers) with the following

```
    "todo-tree.excludeGlobs": [
        "**/*.csv",
        "**/*.cat"
    ]
```

It completes in about 3 minutes 10 seconds, which is great when compared to the time it took before the change by @somewhatabstract.

However, those subfolders are still explored by `rg`, and this is the reason why it takes 3:10 minutes (on 100GB+ of files, which is a lot and probably not common).
I found *excluding whole folders* via the `.rgignore` file to be a better solution for me, because in this case the time taken by `rg` is so short that I don't even notice it.

Finally, thanks a lot for your hard work!

**Comment by somewhatabstract** [comment]
You could use those exclude globs to exclude directories too

**Comment by Thalos12** [comment]
Well, stupid me, I did not think of doing that, so I will try it, thanks!

**Comment by Gruntfuggly** [comment]
Let us know if that worked. :grin:

**Comment by Thalos12** [comment]
It works perfectly! @Gruntfuggly and @somewhatabstract, thanks a lot for your help and for putting up with me on my problem!

**Comment by Gruntfuggly** [comment]
Glad you got it working. :grin:
