### ISSUE TITLE
PLSQL lang support

### ISSUE THREAD

**Issue by JustAPhrog** [Gruntfuggly/todo-tree#180]
Hello,

I'm using plsql in my daily work and I've tried to user this great extension, but in default configuration `todo-tree.regex` is missing `--`.

**Comment by Gruntfuggly** [comment]
Does it work correctly if you add `--` to the regex? I stopped making changes to the default regex because it is impossible to cover every case for all languages and I found that it started breaking existing working configurations.

If you can confirm that adding `--` works for PLSQL, I'll add an entry in the wiki (which I plan to do soon) showing various configurations for different languages, etc.

**Comment by JustAPhrog** [comment]
Yes. I'm confirm - it works.
