### ISSUE TITLE
Block comment TODO not graping

### ISSUE THREAD

**Issue by serkon** [Gruntfuggly/todo-tree#242]
Please update your regexp to ((\*|//|#|<!--|;|/\*|^)\s*($TAGS)|^\s*- \[ \]). It will highlight `comment_block` todos.

```typescript
/**
* Sample typescript class defination
* TODO: sample todo inserted // this to-do is not highlighted
* // TODO: sample todo inserted // this to-do is highlighted
*/
export class SampleClass {}
```

**Comment by Gruntfuggly** [comment]
Hi - thanks for the suggestion. I don't update the default regex anymore because it causes issues for people who are already using it, but obviously you can change it to whatever you need. :grin:

Also, if you add '\n' to the regex, it will also enable multiline comments, which you might find useful. See https://github.com/Gruntfuggly/todo-tree#multiline-todos.
