### ISSUE TITLE
[feature] ScanMode: git-working-directory, git-local-commits, git-my-changes

### ISSUE THREAD

**Issue by nvirth** [Gruntfuggly/todo-tree#288]
It would be a great feature to support git related scan modes.
Those I can think of, and would be very helpful for me, would be to only show the TODOs:
* From the actual uncommitted changes
* From those commits which I haven't pushed yet
* Show them from anywhere, but filter out those TODOs committed by another users

Motivation: The project I'm working on at the moment is very big, with a lot of developers; all of them freely adding their own TODOs to the repo, which I neither want to see at all, nor want them make the TODO sidebar flooded

**Comment by Gruntfuggly** [comment]
The problem with filtering out at git level is time expense of querying the status. At the moment, the scan takes place (pretty quickly due to ripgrep's speed) and then the tree is populated. I would need to a git log for each file that was found - I think the problem would be that that tree would have to be updated asynchronously, which makes it's all a bit more tricky.

However, other people have ask to be able to filter on git user, so I'll see if I can come up with any ways to keep it quick.

Any ideas much appreciated!

**Comment by Gruntfuggly** [comment]
Sorry, but I don't think I'm ever going to get round to this as it's quite a major change and I think it would have a huge performance impact.
