### ISSUE TITLE
Feature Request: List Todos in Tests

### ISSUE THREAD

**Issue by EdRands** [Gruntfuggly/todo-tree#308]
Not all todos are placed in comments. It would be great if todos in tests were listed as well. For example, in Jest:

```js
it.todo("should do something eventually")
test.todo("should do something eventually")
```

Perhaps with a config option of what syntax to look for, rather than having to figure out how every testing framework hands these.

**Comment by EdRands** [comment]
Okay, after reading the readme more closely, it apepars this may already be possible, wit the right `todo-tree.regex.regex`

**Comment by Gruntfuggly** [comment]
Yes, it should be - if you look at the regex, the first section contains the things that normally prefix the TODO's - like comment characters - it's basically a list of alternatives separated by vertical bars, so you could add `it\.|test\.` to match your examples above. You need to escape the period's because they mean 'any' character.
e.g.
```
((//|#|<!--|;|/\*|^|it\.|test\.)\s*($TAGS)|^\s*- \[ \])
```

**Comment by EdRands** [comment]
That worked, after adding a lowercase "todo" to the list of tags.

Thank you, @Gruntfuggly.
