### ISSUE TITLE
Feature: Allow text selection color to override TODO highlight

### ISSUE THREAD

**Issue by pbarnum** [Gruntfuggly/todo-tree#315]
For me, it is very difficult to see what text I am highlighting with my cursor when I have certain TODO colors enabled. I would like to either set an explicit color for when I select TODO text, or set the z-index of my text highlight higher than the TODO highlight.

![image](https://user-images.githubusercontent.com/6970266/81710024-3d38f600-9427-11ea-848f-3cb8d8f4efdf.png)

Notice that the word `this` is highlighted on line 1 and 3, this is because I selected the word on line 2, and vscode's "highlight similar words" feature kicked in. My issue is that if it wasn't for the other lines, I could never tell if I selected the word `this`.

**Comment by Gruntfuggly** [comment]
Unfortunately, there is no way to set the z-index, or a way to set a colour when you are specifically selecting TODO text (if I understand you correctly).

The one thing you can do is adjust the opacity of the background, which may help. E.g.
```
todo-tree.highilghts.default-highlight: {
    background: "#ff0000",
    opacity: 50
}
```

**Comment by pbarnum** [comment]
I added an opacity of `90` as a work around for the issue. It was just enough for me to notice where my selection starts/ends. Thanks!

Feel free to close the issue, I am leaving it as it would be nice to have a permanent fix.

**Comment by Gruntfuggly** [comment]
I'll close it because I don't think there will ever be a permanent fix - vscode allows extensions to create highlights and just hopes they play nice together. It would probably be difficult to allow priority to be chosen.

What would be nice would be if the selection could have its border styled - I'd like to be able to use a lowish alpha for the background colour, but a solid bright border. Doesn't seem to be an option though at the moment. They are constantly adding new theme settings though, so you never know.
