### ISSUE TITLE
Support grouping by markdown heading

### ISSUE THREAD

**Issue by scolestock** [Gruntfuggly/todo-tree#318]
Love this extension.  I'm using it to track todo's in markdown files, and I'd love if the tree view offered a way to group by the markdown heading a given to do was underneath.
```
# Some Heading
- [ ] Todo 1
- [ ] Todo 2
# Another Heading
- [ ] Todo 3
- [ ] Todo 4
```

**Comment by Gruntfuggly** [comment]
I think I get what you're after, but I'm not sure it's possible without a huge amount of specialist handling. The way the extension searches at the moment, you would have to look for the heading as part of the todo and then create multiple TODOs from the same search result.

Maybe it would be easier to create a specialised version of the extension that just works with markdown files?

That being said, I want to add a way to extract more out of the search results so that results can be grouped by user, for example. If I can make it generic enough, it might be able to cover this case too.

**Comment by scolestock** [comment]
Ahh, sure.  Grouping by more than just file and tag - and instead by some surrounding content - is quite a bit different I suppose.  thanks for the consideration!

**Comment by Gruntfuggly** [comment]
Hi - Sorry, but I don't think I'm going to get round to making any changes to implement this. You might still be able to do something with a multiline regex though.
