### ISSUE TITLE
The highlight incorrect works

### ISSUE THREAD

**Issue by diosby** [Gruntfuggly/todo-tree#326]
Hi! I use custom highlight. It works, but if I use inner block comments '/**', then there does not work configured colors.
![Снимок экрана от 2020-06-04 15-47-50](https://user-images.githubusercontent.com/19969187/83759093-b4a32380-a67b-11ea-87ba-8bfdb493f49e.png)

```jsonc
"todo-tree.general.tags": [
        "BUG",
        "HACK",
        "FIXME",
        "TODO",
        "XXX",
        "WARNING",
        "NOTE",
        "INFO",
        "FIX",
        "IDEA",
        "REVIEW",
        "NB",
        "QUESTION",
        "COMBAK",
        "TEMP",
        "DEBUG",
        "OPTIMIZE",
        "CHANGED",
        "ERROR"
    ],
    "todo-tree.general.statusBar": "current file",
    "todo-tree.general.tagGroups": {
    
        "FIXME": [
            "FIXME",
            "FIXIT",
            "FIX",
            "BUG",
            "ERROR"
        ],
        "NOTE": [
            "INFO",
            "NOTE",
        ],
    },
    "todo-tree.highlights.defaultHighlight": {
        "foreground": "#c678dd" //"symbolIcon.functionForeground"
    },
    "todo-tree.highlights.customHighlight": {
        "NOTE": {
            "foreground": "#61AFEF"
        },
        "FIXME": {
            "foreground": "#DF6A73" //"errorForeground"
        },
        "REVIEW": {
            "foreground": "#e0bd4a"
        },
        "WARNING": {
            "foreground": "#d19a66"
        },
        "IDEA": {
            "foreground": "#98C379"
        }
    },
```

**Comment by Gruntfuggly** [comment]
That's because the inner tags are all treated as part of the same item when part of a multiline (block comment) item.  The custom highlight configuration applies to complete todo items, not just the tags in the text, so they would need to be formatted like a complete todo item (with leading comment characters, etc.).

If you just want to colour keywords individually, I recommend this extension:
https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-highlight
