### ISSUE TITLE
Multiline TODOs not being highlight correctly. 

### ISSUE THREAD

**Issue by patel-jeel92** [Gruntfuggly/todo-tree#329]
> And here's my version:
> 
> ```
> "todo-tree.regex.regex": "((//|#|;|\\*)[ ]*($TAGS)[^\\n]*)|(/\\*(\\*?\\s*)*($TAGS)(.|\\n|\\r)*?\\*/)|()"
> ```
> 
> I just slightly modified @tylerbrockett version to allow this kind of TODO, that I use regularly:
> 
> ```
> /**
>  * Some comment
>  * TODO here is a test
>  */
> ```
> 
> https://regex101.com/r/7RRG5c/5

This is a much simpler regex that does the same thing:

`"todo-tree.regex.regex": "(?:(?://|#|<!--|;|/\\*\\*?|\\*)\\s*($TAGS)|^\\s*- \\[ \\])"`

Starting with the default regex, I made the capturing groups non-matching (except the one that needs to be), and I added `\\*?|\\*` to support multi-line JS-style comments. That's it. The default regex doesn't match the entire comment, since all you need to find is the TODO part. I don't see why you'd need to match to the end of the comment.

https://regex101.com/r/q7VcL3/1

_Originally posted by @mbomb007 in https://github.com/Gruntfuggly/todo-tree/issues/255#issuecomment-574279033_

I am using the above regex in my settings.json file and i have a multiline TODO such as 
> // TODO this is a todo
> // continuation of a todo .

and it only highlights the first line.

**Comment by mbomb007** [comment]
From the [comment](https://github.com/Gruntfuggly/todo-tree/issues/255#issuecomment-575229932) right after mine: 

> The reason I prefer not to enable multi-line TODOs by default is that **they are too many potential formats**. The extension searches all files regardless of type, **so it really is up to the user to customise the regex to make it work for them**. As you've found, the regex can quickly get complicated, so it would be very difficult to try and maintain a default regex that works for everybody.
> 
> I've added the regexs above to the wiki page though.

So it's not an "issue". It's something you have to customize to suit your needs. In my regex, my only need was to match the TODO part for highlighting. I don't highlight the comment itself. I also don't consider what you posted to be a multi-line comment, because it uses single-line comment syntax.

Feel free to experiment on Regex101 and adjust the regex to your own needs.

**Comment by tylerbrockett** [comment]
> This is a much simpler regex that does the same thing:

If your claim is that your new regex does the same thing in the comment you quoted, I disagree.

**Comment by Gruntfuggly** [comment]
@patel-jeel92  Is there an actual issue here? As far as I can see, you've changed the regex and it doesn't work, but that's not necessarily an issue with the extension - multiline matches definitely do work, so you might need to change the regex.

One thing to bear in mind is that the regex is a rust regex, not javascript, which means there are some slight differences and some features are not supported (for speed reasons) - please see ripgrep documentation for details:
https://github.com/BurntSushi/ripgrep

**Comment by patel-jeel92** [comment]
You are correct, I just have to make sure i need the correct regex. I will close this issue and its not a real issue
