### ISSUE TITLE
Gutter icons not showing

### ISSUE THREAD

**Issue by Gruntfuggly** [Gruntfuggly/todo-tree#335]

**Comment by Gruntfuggly** [comment]
Can't reproduce this now. @theRenard - are you still seeing this?

**Comment by theRenard** [comment]
Yup

<img width="197" alt="image" src="https://user-images.githubusercontent.com/61255863/87009726-de44f280-c1c5-11ea-9c25-558d88ede123.png">

**Comment by Gruntfuggly** [comment]
Sorry - I'm not sure I understand the screenshot? The gutter icons should be shown in margin of the editor window.

Are you saying that you're not seeing the extension in the activity bar context menu? Does the extension show up at all?

**Comment by theRenard** [comment]
Sorry, should have commented...

<img width="356" alt="image" src="https://user-images.githubusercontent.com/61255863/87010294-a4282080-c1c6-11ea-88bf-91472b118855.png">

As you can see the extension is installed but not shown into left-bar or context menu. I can see the counter in the bottom bar, but nothing happens if I click there.

<img width="40" alt="image" src="https://user-images.githubusercontent.com/61255863/87010396-ccb01a80-c1c6-11ea-8730-9d8893cf22d3.png">

**Comment by Gruntfuggly** [comment]
Oh that's odd. Could it have been accidentally dragged into the bottom panel? Could you also check to see if there us anything in the developer console (Help->Toggle Developer Tools).

**Comment by theRenard** [comment]
You're right, I've found it in the bottom panel! Don't know how it moved there 🤪

**Comment by Gruntfuggly** [comment]
You should be able to drag it back to the activity bar.

I've done it myself - it's nice being able to move stuff around, but annoying when you do it accidentally!

I'm going to close this issue now.
