### ISSUE TITLE
Option to use next line when there is nothing after the tag?

### ISSUE THREAD

**Issue by Amanita-muscaria** [Gruntfuggly/todo-tree#339]
f.x.
```Python
# TODO
def foo(self) -> Any:
    raise NotImplementedError
```

Instead of just showing "TODO" in the tree, it would additionally use the next line (in this case the function). It gives a little better context if someone (probably me) was too lazy to type out an entire todo message.

**Comment by Gruntfuggly** [comment]
To make this work, you will need to enable multiline searching. See https://github.com/Gruntfuggly/todo-tree#multiline-todos (and https://github.com/Gruntfuggly/todo-tree/wiki/Configuration-Examples for more examples).

By including more lines (using a multiline regex) it should work automatically.

Unfortunately, this is the only way it can work because the tree can't easily retrospectively look into the files for more data.

**Comment by Amanita-muscaria** [comment]
Ah, I see. Thanks!

**Comment by Gruntfuggly** [comment]
If you get something working, can you post the regex here and I'll add it to the wiki. 🙂
