### ISSUE TITLE
Causes lots of slowness when enabled

### ISSUE THREAD

**Issue by erothmayer** [Gruntfuggly/todo-tree#377]
I discovered that when Todo Tree is enabled on a reasonably-sized Java workspace over SSH Remote, a bunch of things become really slow. The terminal in VSCode freezes for ~10-15 seconds after saving a small file. Intellisense takes forever. "Organize imports" takes forever. Disabling Todo Tree fixed all of this.

Interestingly, there wasn't any apparent CPU spike during this time, so I'm not sure what it was doing.

It may be that our build system has some large directories which I should be excluding, but this still raises a few problems I believe should be addressed in Todo Tree:

1) discoverability. If Todo Tree is freezing parts of the system for 10+ seconds because some files need to be excluded, tracking that down is difficult. It would be good to measure the time the extension is taking to perform actions, and throw up an alert advising the user that they have a config problem when those actions take more than some small amount of time.
2) blocking behavior. I don't understand why this extension should be able to freeze the remote terminal. Something about how it is operating seems to be excessively blocking resources needed by VSCode. Throttling use of those resources or making them non-blocking seems prudent.
3) refresh scope. Since it seems to block for 10+ seconds when saving a single file, it seems that the problem might have to do with re-checking ALL the files whenever ANY file is changed. If that's the case, the plugin could be more tactical about updating only what's changed, and potentially side-step the two problems above.

Happy to provide some more debug info if that would be helpful. Thanks!

**Comment by Gruntfuggly** [comment]
Hi - thanks for the feedback. One obvious thing I can do is add timestamps to the log messages in the debug console. That may help indicate where it's spending time. 

I have also just published a new version which adds a new scan mode (workspace only) which may help. There are four modes:
- Scan Workspace and Open Files
- Scan Workspace Only
- Scan Open Files
- Scan Current File Only
It would be interesting to compare the results.

In general The parts of the process which may be involved are
a) scanning of the folders in the workspace
b) refreshing open files

My guess is that a) is the problem here because it is working remotely, although the extension itself doesn't do much more than than generate a command and run it in a child process. It seems odd that it causes so much blockage of everything else though. It may be because by default ripgrep uses multiple threads, so you could try setting `-j 1` in the `todo-tree.ripgrep.ripgrepArgs`.

I don't think refreshing open files will be a problem because that should all be done in memory.

I'll add timestamps to the debug logging for the next version and let you know when it's available.

**Comment by Gruntfuggly** [comment]
Hi - did you get any further with this? I added timestamps to the logging back in October, so hopefully it might be possible to see where the delays are being caused.

**Comment by Gruntfuggly** [comment]
Hi - I'm going to close this. If there are any further updates, please feel free to re-open.
