### ISSUE TITLE
Filter/Ignore some folders

### ISSUE THREAD

**Issue by mcunha98** [Gruntfuggly/todo-tree#388]
Hi,

How can I filter some paths to ignore on list of TODO/FIXME ?
For example my folder VENDOR has js and other files and they your own FIXME/TODO tags into, and I want to see only my tags on project.

**Comment by USAFrenzy** [comment]
If you look through the documentation on the home page, there's an option called ```"todo-tree.filtering.excludeGlobs"``` .  When you hover over the option in the 'settings.json', you'll find that the exclude globs have exactly what you're looking for.  Luckily, in your case, it may be as simple as just adding ```"**/VENDOR/**"``` to that field so that it's : ``` "todo-tree.filtering.excludeGlobs":  { "**/VENDOR/**"  },``` in your settings judging by the lowercase version in the default field. I wish I knew more on regex patterns, but hopefully just knowing about that setting variable will help ya!

**Comment by Gruntfuggly** [comment]
You can also right click in the tree to hide folders and individual files

**Comment by mcunha98** [comment]
@Gruntfuggly and @USAFrenzy  thanks for reply.
Just to confirm, I did something wrong ???
![image](https://user-images.githubusercontent.com/6831010/98948946-dd0a3600-24d5-11eb-9c56-7462f4970ac0.png)

My settings:
```
    "todo-tree.filtering.excludeGlobs": [
        "\"**/VENDOR/**\""
    ],

```

**Comment by Gruntfuggly** [comment]
Did you get it working? I got an email asking if something was wrong, but the message doesn't appear here?

**Comment by mcunha98** [comment]
Thanks,

Works fine, just to remember that parameter is **case sensitive**.
![image](https://user-images.githubusercontent.com/6831010/98949171-1b9ff080-24d6-11eb-9539-9c17533d8c37.png)

Now I really see only that I need , thanks again.
Note: as I working on config, I did some changes on my config, , is really very nice to dod
![image](https://user-images.githubusercontent.com/6831010/98949328-53a73380-24d6-11eb-8832-e6a184aadeec.png)

**Comment by Gruntfuggly** [comment]
Yes - the paths are all case sensitive. 😄 

Are you OK if I close this issue now?

**Comment by mcunha98** [comment]
Sure, thanks again !!!
