### ISSUE TITLE
Gruntfuggly.todo-tree\pattern.txt: The system cannot find the file specified

### ISSUE THREAD

**Issue by gmccullo** [Gruntfuggly/todo-tree#399]
Started getting this error _a lot_ today:

todo-tree: c:\Users\gary\AppData\Roaming\Code\User\workspaceStorage\ada994e5816b9ca7e2d1265a11d4e2cd\Gruntfuggly.todo-tree\pattern.txt: The system cannot find the file specified. (os error 2)

**Comment by Gruntfuggly** [comment]
Where are you seeing it - in a popup?

**Comment by Gruntfuggly** [comment]
Please can you try "Todo Tree: Reset Cache".

If that doesn't help, in the short term, you can set `todo-tree.ripgrep.usePatternFile` to `false`. 

If you have time, could you re-install the previous version (0.0.188) and see if it goes away?

There was a recent fix to address an issue where it was failing to delete pattern file, but this looks like it's failing to create it in the first place.

**Comment by RobertKlohr** [comment]
I'm getting the same issue after upgrading to 1.90.  Running  "Todo Tree: Reset Cache" did not resolve the issue.  I'm not sure if it's related but the Todo Tree icon is also now missing from the side bar.

Reverting to 1.88 seems to resolve the missing pattern.txt file issue but the Todo Tree icon is still missing.

**Comment by Gruntfuggly** [comment]
Did setting `todo-tree.ripgrep.usePatternFile` to `false`, stop the error?

The icon missing from the side bar is probably because it hasn't found any todos. Can you set 
`todo-tree.tree.hideTreeWhenEmpty` to `false` and see it it reappears? 

I think I need to change the default for that setting.

**Comment by Gruntfuggly** [comment]
Please could you enable `todo-tree.general.debug` please and see what is shown in the Todo Tree output channel? (View->Output, then select Todo Tree from the dropdown)

It should say if it has failed to create the pattern file.

**Comment by RobertKlohr** [comment]
The missing icon is not due to not having Todo, (I have hundreds in this project!).  Manually dragging the header from the Explorer view to the sidebar reset the icon.

I had to go back to version 1.87 to stop the error messages.  Hopefully that helps with identifying where the issue started.

Will update back to 1.90 and set todo-tree.ripgrep.usePatternFile and todo-tree.general.debug and post the results back here.

Can you provide a short summary as to the purpose of the pattern file and if/how it is related to ripgrep?  I'm am curious to see if this could be related to my install install of ripgrep and/or another extension that is using that install since I had this extension set to use that installation.

**Comment by RobertKlohr** [comment]
Upgraded back to 1.90.  I noticed this time that on the reload from the install that the icon in the sidebar does get removed but then is added back.  I'm guessing this is normal during an upgrade and for some reason the first time I upgraded that step failed but on this last attempt there was no problem.

As for the pattern.txt file issue here are the lines from the debug output:

```
12:07:08.821 Writing pattern file:c:\Users\dummy\AppData\Roaming\Code\User\workspaceStorage\fd17bae514ae56ecde43e6e045242367\Gruntfuggly.todo-tree\pattern.txt
12:07:08.827 Pattern:((//|#|<!--|;|/\*|^)\s*(TODO|FIXME|BUG)|^\s*- \[ \])
12:07:08.828 Command: "c:\Users\dummy\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 --no-config  --no-ignore --hidden  -f "c:\Users\dummy\AppData\Roaming\Code\User\workspaceStorage\fd17bae514ae56ecde43e6e045242367\Gruntfuggly.todo-tree\pattern.txt" "c:\Users\dummy\AppData\Roaming\Code\User\sync"
12:07:09.953 Search failed:
c:\Users\dummy\AppData\Roaming\Code\User\workspaceStorage\fd17bae514ae56ecde43e6e045242367\Gruntfuggly.todo-tree\pattern.txt: The system cannot find the file specified. (os error 2)

12:07:10.154 Search failed:
c:\Users\dummy\AppData\Roaming\Code\User\workspaceStorage\fd17bae514ae56ecde43e6e045242367\Gruntfuggly.todo-tree\pattern.txt: The system cannot find the file specified. (os error 2)

12:07:10.154 Found 1540 items
```

I checked and the folder c:\Users\dummy\AppData\Roaming\Code\User\workspaceStorage\fd17bae514ae56ecde43e6e045242367\Gruntfuggly.todo-tree\ is empty.

I then disabled todo-tree.ripgrep.usePatternFile so that the pattern is passed on the command line to ripgrep and as expected the error stopped.

The difference is now the output shows:

**_Found 76 items_**  instead of **_Found 1540 items_** 

This is consistent (the 76 count) with the number of Todo tags I have in the workspace I am using to test.

I then looked back at the output log and noticed that the Found items count actually started at 76 when the extension first loaded and then grew in size each time files in the workspace (mostly related to .git and file syncs) changed.

I'm attaching the [todo-output.txt](https://github.com/Gruntfuggly/todo-tree/files/5661725/todo-output.txt) here so you can look through the entire file.  I made the change to the todo-tree.ripgrep.usePatternFile setting at 12:11:44.544.

**Comment by Gruntfuggly** [comment]
The extension used to have two views (because it was created before you could move views with drag and drop). To simplify it, one of the views has now been removed. That's probably why it looked like the icon disappeared - when the view is in the explorer pane, it doesn't get shown in the activity bar.

The pattern file is used as an alternative to passing the regex to ripgrep as a command line argument. It avoids having to escape some characters and avoid some other issues where characters don't seem to get passed correctly. It's created in a temporary folder (provided by vscode for the extension) and the filename is passed as an argument to ripgrep instead.

Out of interest, what version of ripgrep are you using? 

If your regex is simple (or the default), you don't actually need to use the pattern file, so you can safely set `todo-tree.ripgrep.usePatternFile` to `false`.

I think the found item count is going wrong because the search is failing - I'll take a look at that.

**Comment by Gruntfuggly** [comment]
Looking at your log, it looks like you're using the file system watcher. It looks like its triggering multiple searches.

Could you try disabling the file watcher and seeing if it makes any difference? Out of interest, why are you using it? I added it because some people asked for it, but I'm not sure it's genuinely that useful.

I think whats happening is the that the first search finishes and deletes the pattern file, but the second search is still using it. I'll make a change to making the pattern filename unique for each search.

**Comment by Gruntfuggly** [comment]
I've uploaded a version which uses unique names for the pattern file. Hopefully this will stop this issue happening, although I still need to look at why the count is wrong when the search fails.

**Comment by RobertKlohr** [comment]
### todo-tree.general.enableFileWatcher
The reason I enabled todo-tree.general.enableFileWatcher was that it just seemed like a good way to ensure I was always looking at the currently list of Todo entries.  How/when is the list updated if it is not triggered on file changes?  I would have assumed this would have been the default trigger but I have no understanding of the internals of VSCode when it comes to extensions and triggers.


### 1.90 Testing
I reloaded 1.90 and reset both tree.ripgrep.usePatternFile and todo-tree.general.enableFileWatcher to their default settings and the problem did does not happen.  If I watch the folder I can see the pattern.txt file being written and deleted.  I think this confirms you idea about overlapping searches.


### 1.92 Testing
 I upgraded to 1.92 and if I watch the folder I can see the <random name>.txt file being written and deleted.

I then renabled todo-tree.general.enableFileWatcher and everything continued to work without any errors.  If I watch the folder I can see the multiple (never more than 2) <random name>.txt file being written and deleted.

**Comment by Gruntfuggly** [comment]
Great - so that sounds like it's fixed then?

You don't really need the file watcher unless files in the workspace are being changed by other processes (in another editor for example). Changes made within code are picked up automatically.
