### ISSUE TITLE
Support Haskell comments

### ISSUE THREAD

**Issue by NiekPas** [Gruntfuggly/todo-tree#442]
Todo tree does not yet support Haskell-style comments by default:

```
-- TODO implement
myFunc = undefined
```

I'm not familiar with the codebase, but looking through it, this seems to be a one-liner fix:

```
package.json:712 
"todo-tree.regex.regex": {
  "default": "((//|#|<!--|;|/\\*|^)\\s*($TAGS)|^\\s*- \\[ \\])",
  # Change to:
  "default": "((//|#|<!--|;|/\\*|--|^)\\s*($TAGS)|^\\s*- \\[ \\])",
  "markdownDescription": "%todo-tree.configuration.regex.regex.markdownDescription%",
  "type": "string"
},
```

**Comment by Gruntfuggly** [comment]
Hi - I no longer make updates to the default regex because every time I did it caused problems for people who use it. I broke my own rule a few months ago thinking it wouldn't cause a problem and it immediately did, so I had to revert it. 😠 

You can obviously modify the setting for your own use though.

I am in the middle of trying to fix the extension to allow multi-line Haskell comments (see #407). Once I get it working, I'll update the wiki with examples for Haskell.

**Comment by Gruntfuggly** [comment]
Hi - I've now got the multiline comments working (with a bit of a hack), so I've added a regex to the wiki for Haskell use.

It should work with the latest version (0.0.207). Re-open this if you have any problems.
