### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by abelfubu** [Gruntfuggly/todo-tree#478]
- Issue Type: `Performance`
- Extension Name: `todo-tree`
- Extension Version: `0.0.208`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.55.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\abelf\AppData\Local\Temp\Gruntfuggly.todo-tree-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Gruntfuggly** [comment]
Hi - are you actually seeing an issue with the extension, or is this just being reported from the extension host? I see these reports from extensions which don't actually do anything, so to be honest I don't really trust them.

However, the extension is likely to cause high load if you have a large workspace because it is scanning all the files.

Can you post your extension settings and some information about your workspace?

**Comment by abelfubu** [comment]
Yep, you are right its reported form extension host and I am currently working in a huge angular workspace so just dissmiss the comment, just wanted to inform of the issue just in case someone else was having it.

Thanks for the reply and for the great extension btw!!!

**Comment by Gruntfuggly** [comment]
No problem. If you do run into any performance issues, there are some settings that can be tweaked to help.

**Comment by Utkarsh-Kumar384** [comment]
@Gruntfuggly Hello, 
Could you mention some of the tweaks and performance improvements that you were saying?

I am currently having issues with opening projects that are just about a gigabit in size. My laptop is just not responsive for the first 30 seconds or so. 

I did try to google up ways to "delay the start of the extension" so that the extension loads after other extensions are done loading so that I don't get bombardment by the initial lag of opening vs code. However, I couldn't find any methods of doing so :(

Thanks in advance
