### ISSUE TITLE
Feature: Task Count Badge on Activity Bar

### ISSUE THREAD

**Issue by pcleckler** [Gruntfuggly/todo-tree#485]
It would be helpful if Todo Tree would show a grand total count of all tasks found as a badge overlaying the tree icon. Then, a developer would only have to glance at the Activity bar to know if there were outstanding tasks.  Much like Source Control pending changes or the Problems view icons.

**Comment by Gruntfuggly** [comment]
Hi - you're not the first person to request this. 🙂 

Unfortunately there is not API to provide it at the moment. 

https://github.com/microsoft/vscode/issues/108496
https://github.com/microsoft/vscode/issues/62783

As soon as VSCode allows it, I'll add it to the extension.

**Comment by pcleckler** [comment]
I figured not, but did not see the feature request in GitHub. I also did
not look very hard!

Thanks for letting me know. Enjoying Todo Tree.

**Comment by metasean** [comment]
@Gruntfuggly - Can you re-open this ticket?  It looks like VSCode is finally going to be getting the necessary API.


> @hamirmahal glad to hear you are interested in this API. We have slowly started to work on this feature with the help of @matthewjamesadam For now no further help from the community is required. Thank you for offering though!
https://github.com/microsoft/vscode/issues/62783#issuecomment-1015418185


@hamirmahal says that they don't need help from the _community_, however, since `todo-tree` was [literally one of the first examples](https://github.com/microsoft/vscode/issues/62783) given for where this API would be useful, I suspect they might appreciate _your_ feedback at some point during their API update process.

**Comment by Gruntfuggly** [comment]
Don't worry - I read the release notes as soon as they come out and check for any updates to the API. As soon as it's available, I'll add it. :smile:
