### ISSUE TITLE
Allow to assign pre-defined categories to patterns

### ISSUE THREAD

**Issue by letmaik** [Gruntfuggly/todo-tree#5]
It would be really neat if there were a few pre-defined categories like "TODO" and "FIXME" such that each pattern is assigned to one. Based on that, there could be a new feature for filtering by category and even optionally displaying icons in the leaves depending on the category, where FIXME could be red and TODO yellow or something like that.
Some inspiration: https://www.python.org/dev/peps/pep-0350/#examples

**Comment by Gruntfuggly** [comment]
Hi - I've just uploaded a version that supports icons from the current icon theme and allows you to configure the colour of the todo item icon. I'll see if multiple categories can be done, but it might not be a simple as it looks...

**Comment by letmaik** [comment]
If it's always the same color then it doesn't add any semantic information. I would only add icons if there's a way to distinguish different cases, otherwise it's a pointless I think.

**Comment by Gruntfuggly** [comment]
I was already in the process of adding the icons from the theme now that vscode supports it, but I realise that's not exactly what you were suggesting. 

The difficulty is that the search uses a single regex with a group for the tags (TODO, FIXME, etc.) so the different coloured icons would probably need to be a secondary function rather than based on the search.

This would mean that the config would really need a separate setting for the colour which could conflict with the regex. But I will try to add it as an extra feature to base the colour on the result.

**Comment by Gruntfuggly** [comment]
Hi there - latest version now supports colours based on the tag.

**Comment by letmaik** [comment]
Great! Works for me.
The description for `iconColour` is missing the available colours though.

**Comment by Gruntfuggly** [comment]
I see what you - they're only in the readme. I'll add them...
