### ISSUE TITLE
todo-tree: Error: stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by matrixapps** [Gruntfuggly/todo-tree#55]
Since installing newest version of VSCODE (Version: 1.25.1 Windows) the extension constantly generates the following error and nothing shows up in todo list

todo-tree: Error: stdout maxBuffer exceeded

**Comment by Gruntfuggly** [comment]
Please try changing `todo-tree.ripgrepMaxBuffer` to a number higher than 200. Sounds like you must have quite a lot of TODOs in your project?

**Comment by matrixapps** [comment]
I actually only have about 60.  I changed to 500; restarted Code and get the same message.  This only started after today's latest VSCode update.

**Comment by Gruntfuggly** [comment]
What sort of files do you have in your workspace? Is it possible it's finding them in minified files?

**Comment by matrixapps** [comment]
It's strange because I created a workspace with a minimal set of files and 3 todo's and the error still shows up; and TODO reads, "nothing found".  Again, this extension has worked flawlessly until today :(
Thanks for your responses.

**Comment by Gruntfuggly** [comment]
There was an update a few days ago to fix exactly the same problem, which is why the ripgrepMaxBuffer setting was introduced. I'm currently trying a different way to solve the problem, so please hang in there...

If you don't mind getting your hands a bit dirty, you could remove the change yourself. If you edit:
  Gruntfuggly.todo-tree-0.0.71/ripgrep.js  
and change line 125 from
`currentProcess = child_process.exec( execString, { cwd, maxBuffer }, ( error, stdout, stderr ) =>`
to
`currentProcess = child_process.exec( execString, { cwd }, ( error, stdout, stderr ) =>`
and see if it works for you again...

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version which handles the buffer processing slightly differently. Please let me know if it works any better for you.

**Comment by matrixapps** [comment]
I just reloaded and it works.  Thanks so much for your incredibly prompt attention!

**Comment by Gruntfuggly** [comment]
That's a relief! Glad it's working again. 8-)
