### ISSUE TITLE
Python docstring TODOs not showing up in the tree

### ISSUE THREAD

**Issue by karimStekelenburg** [Gruntfuggly/todo-tree#552]
Forgive me if this question has already been asked or if this is a matter of configuration. I've searched for issues on this and have read the documentation, but I can't seem to figure this one out.

In Python, it's common to write comments using a docstring. For example:

```python
def foo(bar):
	"""Does some stuff""
```
The comments are surrounded by either triple double quotes (`"""comment"""`), or triple single quotes (`'''comment'''`), and they can be multiline as well.

I would have expected my todo's to show up in the tree if written this way (e.g. `"""TODO: do this thing"""`. Yet, this doesn't seem to be the case.

However, if I put a `#` in front of the todo, it **does** show up in the tree. For example:

This **does not** work:
```python
def foo(bar):
	"""Does some stuff
	TODO: implement stuff
	"""
```

But this **does** work:
```python
def foo(bar):
	"""Does some stuff
	# TODO: implement stuff
	"""
```

I was wondering if this is intended behaviour or a bug/missing feature. If the behaviour is intended, I'd love to know if it's possible to configure todo-tree in a way that allows me to omit the `#` symbol.

Thanks!

**Comment by Gruntfuggly** [comment]
It's because the regex usually looks for some sort of comment character before the "TODO" keyword. For most languages it's something like `//`or `#`.

However, the default regex does also search for whitespace at the beginning of the line followed by the tag, so with the default settings, it works for me:

![image](https://user-images.githubusercontent.com/376658/132880419-5d1cec15-d930-4796-9f3b-60f34d4f2440.png)

What is your regex set to?

Using the default regex, it won't detect 
`""" TODO Does some stuff""""`
If you need that, you need to add `"""` to the regex, e.g.
```
(//|#|"""|<!--|;|/\*|^|^[ \t]*(-|\d+.))\s*($TAGS)`
```
or
```
    "todo-tree.regex.regex": "(//|#|\"\"\"|<!--|;|/\\*|^|^[ \\t]*(-|\\d+.))\\s*($TAGS)"
```
If you're setting it in the `settings.json`

**Comment by karimStekelenburg** [comment]
Hi @Gruntfuggly, thanks for the super quick reply. My regex is set to the default indeed.

You are right, my examples were off. I attempted to do the following instead of putting the TODO on a new line, as my examples suggest:

```python
def foo(bar):
	"""TODO: task
	"""
```

With the default regex it looks like it doesn't work if the `TODO` is put on the same line as the initial `"""`, regardless of the space before `TODO`. However, I don't mind this and putting it on a new line is fine for me. I'm already quite happy I don't have to prefix the `TODO`s with an ugly `#` 🙃!!

Thanks again! I'll give the recommended regex a try!
