### ISSUE TITLE
[Inquiry] Main - Sub TODOs

### ISSUE THREAD

**Issue by FooNagi** [Gruntfuggly/todo-tree#554]
This is actually an inquiry rather than an issue, but is it possible to have groupings under the tags?

Sample data:

![image](https://user-images.githubusercontent.com/43235725/134770008-19b38cae-d722-4155-ae1d-5c24c48cddf3.png)

Current TODO tree:
![image](https://user-images.githubusercontent.com/43235725/134770017-41d6cf41-c825-4ecc-951a-4b77a0e1ffde.png)

Is it possible to have the sub-processes/topics be grouped and indented in the TODO tree view? Perhaps something like this:

![image](https://user-images.githubusercontent.com/43235725/134770069-69657777-1df9-44c2-bb2f-81fe5975d5a5.png)

**Comment by Gruntfuggly** [comment]
If I understand correctly, I don't think so because the extension would have to understand the syntax of the language in order to know that the subprocess TODOs are nested.

You can group them if you put the topic in with each tag, but that would change the layout of your document and is probably not what you want.

**Comment by FooNagi** [comment]
Appreciate the info!
