### ISSUE TITLE
Group By Author

### ISSUE THREAD

**Issue by jingyugao** [Gruntfuggly/todo-tree#60]
In a team project, there are always many todos of other authors, but one might only care his todos.

**Comment by Gruntfuggly** [comment]
Hi - I can see that this would be a useful feature, but how would you propose it would work?

I think the only way you could do it easily is if you could customise the regex so that it only finds todos from an author if you use the format `// TODO (<author>) Fix this`.

Even then, the grouping would be difficult as there are so many ways to specify the author. 

If you have any other ideas of how to implement it, I would be interested to know.

**Comment by jingyugao** [comment]
I am sorry for that I don't express the issue clearly. My idea is that we can use git to find the author who submit the "TODO" line.

**Comment by jingyugao** [comment]
I am learning how to use js to call git's api. But I think it can be implement

**Comment by Gruntfuggly** [comment]
That would be possible, but I think it could be very slow? It could be a background process that gradually populates the data, in order to do grouping when it is finished. You would also have to take into account what happens when a file is editted and the TODO is moved.

One thing thing that would be quite easy, would be to only highlight TODOs by the current author, because the highlighting is only applied to the current file.

**Comment by jingyugao** [comment]
I mean that we can use the commond:
git blame <file> -L<line,line> -p|sed -n '2p'|awk '{print $2}'
to get author.

**Comment by Gruntfuggly** [comment]
That will work, but it might be inefficient for large numbers of TODOs. I will try it and see if it has much impact...

**Comment by jingyugao** [comment]
I just add these code to get author, it seems works but a little slowly.I am trying to use nodegit to replace the shell cmd, I think it will be much quickly.
function getAuthor(repo,file,line)
{
    var exec = require('child_process').execSync; 

    var data=exec("cd "+repo+" && git blame "+file+" -L "+line+","+line+ " -p|sed -n '2p'|awk ")
    return data.toString();
};

**Comment by Gruntfuggly** [comment]
Hi - did you get any further with this?

**Comment by jingyugao** [comment]
I use git command and it seems just ok. emm very slow but is ok to me.
Nodegit is faster but i dont know js.
I think this may be a good feature.

**Comment by Gruntfuggly** [comment]
Can you post me your changes so I can try it?
