### ISSUE TITLE
How to add shortcut when todo-tree view active?

### ISSUE THREAD

**Issue by tjx666** [Gruntfuggly/todo-tree#610]
I tried following, but not works:

```json
{
        "key": "shift+cmd+-",
        "command": "todo-tree.collapse",
        "when": "activeViewlet == 'todo-tree-container.todo-tree-view'"
}
```

**Comment by Gruntfuggly** [comment]
If I use 
```
  {
    "key": "shift+ctrl+-",
    "command": "todo-tree.collapse",
    "when": "activeViewlet =~ /explorer/"
  },
```
it works when the explorer view is active.

But if I try
```
  {
    "key": "shift+ctrl+-",
    "command": "todo-tree.collapse",
    "when": "activeViewlet =~ /todo/"
  },
```
It doesn't work.

I've used the 'Developer: Inspect Context Keys' and it looks like 'activeViewlet' is set to something with a UUID when it's not one of the standard views, probably because of the way that the containers work to allow drag and drop.

You can copy the UUID out of the console and use that in the context clause and it works, but if you move the view out of the activity bar it will create a new UUID.

**Comment by Gruntfuggly** [comment]
I've raised an issue with VSCode here: https://github.com/microsoft/vscode/issues/145118

**Comment by Gruntfuggly** [comment]
Doesn't look like this will ever work. The vscode issue has been closed with very little (and an unhelpful) explanation. Sorry.
