### ISSUE TITLE
Change the default, or document, a good regex for multiline todos in IntelliJ style

### ISSUE THREAD

**Issue by segevfiner** [Gruntfuggly/todo-tree#635]
TODO Tree has support for matching [multiline todos](https://github.com/Gruntfuggly/todo-tree#multiline-todos), yet it is not enabled by default and requires a custom regex to use. The default regex used by TODO Tree matches quite a bunch of different styles of comments for different languages, it would be nice to have a version of it that can match multiline comments in the style matched by the IntelliJ family of IDEs. IMHO It could even be the default, but can otherwise be something that is simply documented in the extension's README.

It is difficult to write a robust regex for this, so it would be nice for a user that wants to use multiline todos to not have to come up with a regex on his own.

**Comment by Gruntfuggly** [comment]
Could you provide some examples? I don't use the IntelliJ family of IDEs so I have no idea what the regex should match.

It will never be the default because the default regex is intended to be fairly simple and just a starting point. 

If you can provide some examples, I'll happily add them to the Wiki (https://github.com/Gruntfuggly/todo-tree/wiki/Configuration-Examples).

**Comment by Gruntfuggly** [comment]
Closing as no more information available. Feel free to re-open if you need to.
