### ISSUE TITLE
Compatibility for Rust & other Languages Please ?

### ISSUE THREAD

**Issue by SirTwsted** [Gruntfuggly/todo-tree#665]
Compatibility for Rust & other Languages Please ?

thanks.

**Comment by Elias-Graf** [comment]
What exactly is incompatible about it? It really should not matter what language you are using. It uses patterns to detect the to-do comments. In fact, I've been successfully using it in combination with rust.

Are you trying to get it to work for block comments? Because that not really intended: #255. Either modify the regex according to the issue, or just use line comments.

**Comment by Gruntfuggly** [comment]
Closing due to lack of updates.
