### ISSUE TITLE
[Feature Request] Hide ruler highlights in source control editor

### ISSUE THREAD

**Issue by lonix1** [Gruntfuggly/todo-tree#670]
When the source control editor is showing a diff view, the ruler on the right also shows all the document's todo items. That makes it hard to tell at a glance which are the changes and which are the todos.

It would be helpful to disable those ruler todo items, only for the source control editor.

**Comment by Gruntfuggly** [comment]
Bizarrely, when you click in the right hand window of the diff view, the scheme is 'file' which shows TODOs by default. The left hand window scheme is 'git' which doesn't show TODOs (by default).

So you can do the opposite - add 'git' to the `todo-tree.general.schemes` setting to see the ruler makers in both, but not disable them for the right hand side. 

Sadly, there doesn't seem to be any way to do anything with the right hand ruler because it's just a file like the original source file.

Your best best is probably go just disable the ruler markers altogether (set `rulerLane` to none in the default highlight settings).

**Comment by Gruntfuggly** [comment]
I don't think there is much more I can do to fix this, so I'm going to close this now. If anybody can suggest anything, I'm happy to re-open.
