### ISSUE TITLE
flat and expanded Settings unknown

### ISSUE THREAD

**Issue by Chris591** [Gruntfuggly/todo-tree#68]
since the last update these settings are Unkown. Don't know if these need to be configured somewhere else now.

![image](https://user-images.githubusercontent.com/39920986/45209156-82894580-b28c-11e8-9219-eaefadf09e19.png)

**Comment by Gruntfuggly** [comment]
Yes, they are no longer needed as it stores the 'flat', 'grouped' and 'exanded' flags in a different place now (workspaceState) , so there is no need to pollute the user settings with them. You can safely remove them.

They were originally supposed to go in the workspace settings so that your tree view could be configured differently in each window, but if you opened a window without a workspace, then the buttons in the tree view couldn't work because there is no workspace file to update.

**Comment by Chris591** [comment]
OK but now I can't configure it as default or would it use this setting everywere?

**Comment by Gruntfuggly** [comment]
Ah - I see what you mean - you want all views to be flat and expanded when the window is opened. I hadn't considered that anybody would be doing that, sorry!

I'll put them back in as default settings...

**Comment by Chris591** [comment]
thanks

**Comment by Gruntfuggly** [comment]
Restored in the latest version.
