### ISSUE TITLE
multiple tags in the same line

### ISSUE THREAD

**Issue by nitishingde** [Gruntfuggly/todo-tree#72]
My custom settings
```json
{
"todo-tree.tags": [
    "TODO",
    "FIXME",
    "@critical",
    "@high",
    "@low",
    "@today",
    "@by",
  ],
  "todo-tree.highlight": "text",
  "todo-tree.customHighlight": {
    "@critical": {
      "icon": "pin",
      "iconColour": "red",
      "type": "tag",
      "background": "red",
      "foreground": "black"
    },
    "@high": {
      "icon": "pin",
      "iconColour": "yellow",
      "type": "tag",
      "background": "yellow",
      "foreground": "black"
    },
    "@low": {
      "icon": "pin",
      "iconColour": "cyan",
      "type": "tag",
      "background": "cyan",
      "foreground": "black"
    },
    "@today": {
      "icon": "calendar",
      "iconColour": "red",
      "type": "tag",
      "background": "red",
      "foreground": "black"
    },
    "@by": {
      "icon": "calendar",
      "iconColour": "blue",
      "type": "tag",
      "background": "blue",
      "foreground": "black"
    }
  },
}
```
Well i want multiple tags to be processed.
Let me show you an example:
```python
# @low @today
def foo():
    pass
``` 
The problem here is only the first tag `@low` gets recognized.
I tried something like this
```python
# @low # @today
def foo():
    pass
``` 
Well here both the tags got highlighted in my file, but the 2nd `@today` didn't get updated in the tree.

Playing with `"todo-tree.regex": "((//|#|<!--|;|/\\*|^)\\s*($TAGS)|^\\s*- \\[ \\])"` only helped in highlighting the tags properly, but not in recognizing them (well only the first would get recognized as i mentioned before).

Also i wanted to know is it possible for tags with regex like `@by\\[.*\\]` to recognize something like `@by[3:9:18]`

Btw i found your extension quite helpful and i want to thank you for that. (don't want to come off as a cry baby just by complaining here XD)

**Comment by Gruntfuggly** [comment]
I see what you mean - the problem is that the search looks for any of the tags, so it will match the first one and think it's job is done. 

You can get a bit closer to what you want by specifying `--vimgrep` in the `todo-tree.ripgrepArgs` setting. This will show multiple matches in the tree, but the first match will still show the second on the same line because it doesn't know where the first one stops. It's really expected each tag to be following a comment, so I never thought there would be a case for more than one tag.

I could add an option to only display the tag itself in the tree?

Regarding the tags with regex - I think it will work for the highlight because it's done as a secondary process - searching the file for each tag in turn. I think if you define the customHighlight with that tag it will work.  It *might* work for the ripgrep search too - have you tried it? I would use `\d` to match digits, so something like `@by\\[[\d:+]\\]` (off the top of my head)...

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version which supports multiple tags on the same line. Let me know if it works ok...

The regex tag to match "@by[3:9:18]" works fine for the tree view, but it won't actually work for the highlighting at the moment. I'm working on another change which should allow it to work.

**Comment by Gruntfuggly** [comment]
Latest version now handles custom highlights with regexes, so if you put `@by\\[[\d:]+\\]` in the regex, e.g.:
```
"todo-tree.regex": "((//|#|<!--|;|/\\*|^)\\s*($TAGS)|^\\s*- \\[ \\]|@by\\[[\d:]+\\])"
```
and set your customHighlight as:
```
  "todo-tree.customHighlight": {
    "@by\\[[\d:]+\\]": {
      "iconColour": "red",
    },
```
It should work. 😕 

Let me know how you get on! 😁

**Comment by nitishingde** [comment]
> I've just uploaded a new version which supports multiple tags on the same line. Let me know if it works ok...
> 
> The regex tag to match "@by[3:9:18]" works fine for the tree view, but it won't actually work for the highlighting at the moment. I'm working on another change which should allow it to work.

Yes the multiple tag thing works, thanx!!! :+1: 
Well you need wrap each tag in a comment, but i don't that mind :).
Actually, its better, because then you can wrap info of just that tag

Example:
```python
#@high : bug #@today : client wants it by 4pm
def foo(): pass
```
In the tree, one sees
`@tag : bug` 
`@today : client wants it by 4pm`
The info of tags don't get mixed up! It's beautiful.

Good work.
