### ISSUE TITLE
TODO tree makes VSCode slower to start

### ISSUE THREAD

**Issue by aitor-gomila** [Gruntfuggly/todo-tree#752]
Todo tree extension seems to be making my VSCode slower to start. By 72 ms, which is not much, but it's a little extension I use every once in a while so, what is causing this delay?

![Screenshot from 2023-04-18 20 42 51](https://user-images.githubusercontent.com/46191980/232873159-0c6f68e4-fe93-44db-aa0f-05f72c88b535.png)

I can make a PR myself, is someone points out what's causing this? I think it may be the activation points :-)

**Comment by Gruntfuggly** [comment]
72ms is les than 1/10th of a second?! 

It does quite a bit of set up when it starts up, e.g.

```javascript
        migrateSettings();
        validateColours();
        validateIcons();
        validatePlaceholders();
        setButtonsAndContext();
```

It also doesn't activate until the rest of start up has finished. 

I kind of resent the suggestion that it's just a "little extension" - I've been actively working on it for over 5 years and it has grown with features considerably since it started, so it's really not surprising it takes more than 0 milliseconds to start.

Feel free to create a PR, but I'm not likely to merge anything that removes features just to save a fraction of a second.

**Comment by ghost** [comment]
Oh, don't take me wrong. You put significant effort to create this extension. And I understand that.

I will message back when I detect what ia causing the slow down.

**Comment by zuibunan** [comment]
![image](https://github.com/Gruntfuggly/todo-tree/assets/3386786/e9a3c24e-6e4c-4994-afd0-7d53ece8295d)
Todo tree makes my VSCode lag while 'scanning the workspace for Git repositories' for a long time. After disabling Todo Tree, it only takes a few seconds.
