### ISSUE TITLE
Razor comments

### ISSUE THREAD

**Issue by Neogamezzz** [Gruntfuggly/todo-tree#818]
How to exclude symbols "*@" at end of Razor comments?

I have this regex "((@\*|//|/\*|<!--)\s*($TAGS))" and it matches properly the symbols that are at the end of comments in all other file types except .razor.

<img width="851" alt="Razor" src="https://github.com/Gruntfuggly/todo-tree/assets/47366635/abd1e6f0-95ef-4dca-85a6-bb9399baea59">

<br />
<br />
For example, in .html files it works fine:
<br />

<img width="723" alt="HTML" src="https://github.com/Gruntfuggly/todo-tree/assets/47366635/f4a37efb-6382-4f27-8a6a-d1c3d1077f23">

**Comment by suuppl** [comment]
if you aren't using subtags, you can use
```json
"todo-tree.regex.subTagRegex": "(@*)",
```

Edit: This is wrong, the `*` isn't escaped for a start. Also the order is wrong, sorry 😬) As soon as i get around to test it, I'll add another edit.

**Comment by Neogamezzz** [comment]
No effect.
I wrote:

"todo-tree.regex.regex": "((@\\*|//|/\\*|<!--)\\s*($TAGS))",
"todo-tree.regex.subTagRegex": "(@*)",

Maybe I have the wrong regex?

**Comment by suuppl** [comment]
I think i misunderstood what you meant before. Can you try this?
```json
"todo-tree.regex.subTagRegex": "((?:.(?!\\*@|-->).*?)*)"
```
and swap out `${after}` for `${subTag}` in `"todo-tree.tree.labelFormat"`
(the default value would become
```json
"todo-tree.tree.labelFormat": "${tag} ${subTag}"
```
)

The idea here is to match everything except the ends of comments (`*@`, `-->`) as the subtag and just use the subtag as text.

otherwise, you could maybe try to match the ends of the comments as subtags (`.*(\\*@|-->)\\s*` or something? The capture group is important, whatever is in there will be treated as the subtag.)

I haven't tested any of this yet, when i get to it, I'll update my answer.

**Comment by suuppl** [comment]
> No effect.
> I wrote:
> 
> "todo-tree.regex.regex": "((@\\*|//|/\\*|<!--)\\s*($TAGS))",
> "todo-tree.regex.subTagRegex": "(@*)",
> 
> Maybe I have the wrong regex?

First thing I would try is `".*(\\*@)"` for the subTagRegex.

**Comment by Neogamezzz** [comment]
You are great! Thank you man!

```
"todo-tree.tree.labelFormat": "${tag} ${subTag}",
"todo-tree.regex.regex": "((@\\*|//|/\\*|<!--)\\s*($TAGS))",
"todo-tree.regex.subTagRegex": "((?:.(?!\\*@|-->).*?)*)",
```
